### ISSUE TITLE
version = libraryVersion

### ISSUE THREAD

**Issue by javakam** [panxw/android-volley-manager#8]
Error:(5, 0) Could not find property 'libraryVersion' on project ':library'.
<a href="openFile:C:\fastwork\AceMaster\library\build.gradle">Open File</a>

**Comment by SeongminHeo** [comment]
How to use set http headers ?
not find is it.....

**Comment by SeongminHeo** [comment]
.request use thx

**Comment by djonce** [comment]
@SeongminHeo The project does not provide this setting function, the project is currently only easy to play the media without having to pay attention to detail, you can fork this project add function for yourself. I have a Google MediaPlayer Http header added some of the discussions, I hope to help you.

http://stackoverflow.com/questions/8959300/how-do-i-include-http-headers-with-mediaplayer-setdatasource

**Comment by javakam** [comment]
复活😂

**Comment by panxw** [comment]
gradle.properties
